#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-toml
Version  : 0.7.0
Release  : 1
URL      : http://pypi.debian.net/toml/toml-0.7.0.tar.gz
Source0  : http://pypi.debian.net/toml/toml-0.7.0.tar.gz
Summary  : Python Library for Tom's Obvious, Minimal Language
Group    : Development/Tools
License  : MIT
Requires: python-toml-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : setuptools

%description
TOML
====
See also https://github.com/mojombo/toml
Python module which parses and emits TOML.

%package python
Summary: python components for the python-toml package.
Group: Default

%description python
python components for the python-toml package.


%prep
%setup -q -n toml-0.7.0

%build
export LANG=C
python2 setup.py build -b py2

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
